Repository FRONTENDSCHOOL10/hexagon-potatoes, pull requests merged in 2024-09, with the labels that each got.

#7 fix : build 관련 경고 메세지 처리
  package.json
  postcss.config.js
Labels: 🐛 fix

#15 src : 스프라이트 이미지 추가
  public/assets/sprite-sheet.svg
Labels: 🎞 src

#4 feat : shipstate 컴포넌트 구현
  src/components/shipstate/Shipstate.tsx
Labels: 🎨 feat

#9 feat : payment 컴포넌트 제작
  src/components/Payment/Payment.tsx
  src/components/Payment/PaymentListItem.tsx
  src/utils/useCurrencyFormat.tsx
Labels: 🎨 feat

#12 feat : 별점 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  src/components/RatingStar/RatingStar.tsx
Labels: 🎨 feat, 🐎 ci

#18 docs : 환경설정 및 라이브러리 추가
  package.json
  pnpm-lock.yaml
  prettier.config.js
  tsconfig.json
Labels: 📝 docs, 🐎 ci

#22 feat : 매거진 컴포넌트 제작
  src/components/Magazine/Magazine.tsx
Labels: 🎨 feat

#25 feat : 헤더, 네비, 경로 설정중
  src/App.tsx
  src/components/HeaderBar/HeaderBar.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/hooks/useHeaderConfig.ts
  src/layout/RootLayout.tsx
  src/pages/BoastDetail.tsx
  src/pages/ChatHome.tsx
  src/pages/Community.tsx
  src/pages/HomePage.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Notifications.tsx
  src/pages/PartyCollect.tsx
  src/pages/PartyDetail.tsx
  src/pages/Search.tsx
  src/pages/SearchResult.tsx
  src/pages/Setting.tsx
  src/pages/SignUp.tsx
  src/pages/TipDetail.tsx
  src/router.tsx
Labels: 🎨 feat

#23 Feature/article/jubi
  src/components/ArticleList.tsx
  src/components/Articles.tsx
  src/components/ItemList.tsx
  src/components/Items.tsx
Labels: 🎨 feat

#29 src : 스프라이트 이미지 업데이트
  .github/PULL_REQUEST_TEMPLATE.md
  public/assets/sprite-sheet.svg
Labels: 🎞 src, 📝 docs

#26 feat: search bar 컴포넌트 제작
  src/components/SearchBar.tsx
  src/components/index.js
Labels: 🎨 feat

#30 feat : 사용자후기 컴포넌트 제작
  pnpm-lock.yaml
  src/components/RatingStar/RatingStar.tsx
  src/components/Review/Review.tsx
Labels: 🎨 feat

#35 refactor : 파일명 수정 및 경로수정
  src/components/Payment/Payment.tsx
  src/components/Payment/PaymentListItem.tsx
  src/utils/currencyFormat.ts
Labels: 🎁 modi

#38 feat: 국가 선택 버튼, 일반 버튼 컴포넌트 생성 및 list 컴포넌트 파일 이동
  src/components/Button/Button.tsx
  src/components/Button/SelectCountryButton.tsx
  src/components/Lists/ArticleList.tsx
  src/components/Lists/Articles.tsx
  src/components/Lists/ItemList.tsx
  src/components/Lists/Items.tsx
Labels: 🎨 feat

#39 refactor: input 컴포넌트 리팩토링
  src/components/Inputs/AddressInput.tsx
  src/components/Inputs/EmailInput.tsx
  src/components/Inputs/IdInput.tsx
  src/components/Inputs/NickNameInput.tsx
  src/components/Inputs/PhoneNumberInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/UserNameInput.tsx
Labels: ♻️ refactor

#40 refactor: list 컴포넌트 리팩토링
  src/components/List/ArticleList.tsx
  src/components/List/Articles.tsx
  src/components/List/ItemList.tsx
  src/components/List/Items.tsx
  src/components/List/PartyLeader.tsx
  src/components/List/ParyLeaderList.tsx
Labels: ♻️ refactor

#41 feat, chore, refactor : 컴포 제작, 패키지 설치, 피드백 반영
  index.html
  package.json
  pnpm-lock.yaml
  public/assets/shipmatelogo.png
  src/components/Alert/Alert.tsx
  src/components/HeaderBar/HeaderBar.tsx
  src/components/NavigationBar/FloatingMenu.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/hooks/useHeaderConfig.ts
  src/layout/RootLayout.tsx
  src/main.tsx
  src/pages/BoastDetail.tsx
  src/pages/ChatHome.tsx
  src/pages/Community.tsx
  src/pages/HomePage.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Notifications.tsx
  src/pages/Setting.tsx
  src/pages/SignUp.tsx
  src/pages/Tutorial.tsx
  src/pages/WritePost.tsx
  src/router.tsx
Labels: 🎨 feat, ♻️ refactor, 🐳 chore

#43 feat : 포스팅 카드 컴포넌트 기본작업 및 스프라이트 이미지 수정
  public/assets/sprite-sheet.svg
  src/components/PostingCard/PostingCard.tsx
Labels: 🎨 feat, 🎁 modi, 🧩 markup

#44 💄 Style: tailwind 컬러, 폰트 세팅
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💄 style

#45 modi : 네비게이션 end 추가, 아이콘 변경, 플로팅 메뉴 초기화 추가, 파티 모집 페이지 경로 수정, 테일윈드 관련 수정
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  src/components/NavigationBar/FloatingMenu.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/hooks/useHeaderConfig.ts
  src/styles/global.css
  src/styles/tailwind.css
  tailwind.config.js
Labels: 🎨 feat, 🎁 modi, 📝 docs

#46 style: fontsize와 pretendard import
  src/styles/global.css
  tailwind.config.js
Labels: 💄 style

#47 modi : 폰트 가져오기 위로 옮김
  src/styles/global.css
Labels: 🎁 modi

#49 modi: errored 변수 오타 수정
  src/styles/tailwind.css
  tailwind.config.js
Labels: 🎁 modi

#51 feat : PostingCard 컴포넌트 수정 및 스프라이트 이미지 이슈 해결
  public/assets/sprite-sheet.svg
  src/components/PostingCard/PostingCard.tsx
Labels: 🎨 feat, 🎁 modi, 🎞 src, 🧩 markup

#60 스프라이트 이미지 업데이트, 알럿 svg 가져오기 변경
  public/assets/sprite-sheet.svg
  src/components/Alert/Alert.tsx
Labels: 🎁 modi, 🎞 src

#61 style: Button 컴포넌트 스타일링 및 코드 수정
  src/components/Buttons/Button.tsx
  src/components/Buttons/SelectCountryButton.tsx
Labels: 🎁 modi, 💄 style

#65 style: Search Bar 컴포넌트 스타일링
  src/components/SearchBar/SearchBar.tsx
Labels: 🎁 modi, 💄 style

#66 style: input 컴포넌트 스타일링 및 기본 input 컴포넌트 추가
  src/components/Inputs/AddressInput.tsx
  src/components/Inputs/EmailInput.tsx
  src/components/Inputs/IdInput.tsx
  src/components/Inputs/NickNameInput.tsx
  src/components/Inputs/PhoneNumberInput.tsx
  src/components/Inputs/PwdConfirmInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/StandardInput.tsx
  src/components/Inputs/UserNameInput.tsx
  src/components/List/ArticleList.tsx
  src/components/List/Articles.tsx
  src/components/List/ItemList.tsx
  src/components/List/Items.tsx
  src/components/List/PartyLeader.tsx
  src/components/List/ParyLeaderList.tsx
  src/components/Lists/Article.tsx
  src/components/Lists/ArticleList.tsx
  src/components/Lists/ItemList.tsx
  src/components/Lists/PartyLeader.tsx
  src/components/Lists/ParyLeaderList.tsx
  src/components/SearchBar.tsx
  src/pages/Landing.tsx
  src/utils/validate.ts
Labels: 🎨 feat, 🎁 modi, 🐛 fix, 💄 style, ♻️ refactor

#67 feat : 커뮤니티 페이지 마크업 및 스타일링
  src/components/CommunityNav/CommunityNav.tsx
  src/components/CommunityNav/CommunityNavList.tsx
  src/components/PostingCard/MiniPostingCard.tsx
  src/pages/Community.tsx
  src/pages/Community/Community.tsx
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/Following.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/Community/RecommendFeed.tsx
  src/pages/Community/UserTip.tsx
  src/router.tsx
Labels: 🎨 feat, 💄 style, 🧩 markup

#72 튜토리얼 페이지 제작
  public/assets/landing-1.webp
  public/assets/tutorial-1.webp
  public/assets/tutorial-2.webp
  public/assets/tutorial-3.webp
  public/assets/tutorial-4.webp
  src/pages/Tutorial.tsx
Labels: 🎨 feat, 💄 style, 🧩 markup

#74 랜딩, 로그인, 회원가입 페이지 마크업, 스타일링 | PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
  public/assets/apple.svg
  public/assets/google.svg
  public/assets/kakao.svg
  public/assets/landinglogo.png
  public/assets/loginsignuplogo.png
  src/components/AgreeTo/AgreeTo.tsx
  src/components/AgreeTo/CheckList.tsx
  src/components/Alert/Alert.tsx
  src/components/LoginNavi/LoginNavi.tsx
  src/components/SimpleLogin/SimpleLogin.tsx
  src/hooks/useHeaderConfig.ts
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
Labels: 📝 docs, 💄 style, 🧩 markup

#76 feat: 파티 상세 페이지 마크업 및 스타일링
  src/components/Button/Button.tsx
  src/components/Button/SelectCountryButton.tsx
  src/components/Buttons/Button.tsx
  src/components/Lists/StandardList.tsx
  src/components/PartyInfo/PartyInfo.tsx
  src/components/PartyInfo/PartyInfoList.tsx
  src/components/PostingCard/PostingCard.tsx
  src/pages/Landing.tsx
  src/pages/PartyDetail.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style

#81 feat: 파티 모집 페이지 마크업 및 스타일링
  src/components/Inputs/StandardInput.tsx
  src/pages/JoinParty.tsx
  src/pages/PartyCollect.tsx
  src/router.tsx
Labels: 🎨 feat, 💄 style, 🧩 markup

#82 feat: 주문 상세 페이지 마크업 및 스타일링
  src/pages/OrderDetail.tsx
Labels: 🎨 feat, 💄 style, 🧩 markup

#84 feat: 파티 리스트 페이지 마크업 및 스타일링
  src/components/Lists/Article.tsx
  src/components/Lists/ArticleList.tsx
  src/pages/PartyList.tsx
  src/router.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style

#85 feat : 커뮤니티 페이지 마크업 스타일링 및 데이터 조회
  src/components/Label/LabelList.tsx
  src/components/PostActionBar/PostActionBar.tsx
  src/components/PostingCard/MiniPostingCard.tsx
  src/components/PostingCard/SquarePostingCard.tsx
  src/components/Review/Review.tsx
  src/pages/BoastDetail.tsx
  src/pages/Community/RecommendFeed.tsx
  src/pages/Posting/BlogPosting.tsx
  src/pages/Posting/InstaPosting.tsx
  src/router.tsx
  src/utils/dateFormatter.ts
  src/utils/getPbImageURL.ts
Labels: 🎨 feat, 🎁 modi, 💄 style, 🧩 markup

#87 feat : NameCard 컴포넌트 제작
  src/components/Buttons/Button.tsx
  src/components/Buttons/MiniButton.tsx
  src/components/DefaultProfileSVG/DefaultProfileSVG.tsx
  src/components/NameCard/NameCard.tsx
  src/components/Review/Review.tsx
  src/pages/Posting/InstaPosting.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style, 🧩 markup

#92 feat: input 컴포넌트 기능 수정 및 유효성 검사 로직 조금 수정
  src/components/Inputs/EmailInput.tsx
  src/components/Inputs/IdInput.tsx
  src/components/Inputs/NickNameInput.tsx
  src/components/Inputs/PhoneNumberInput.tsx
  src/components/Inputs/PwdConfirmInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/StandardInput.tsx
  src/components/Inputs/UserNameInput.tsx
  src/utils/validate.ts
Labels: 🎨 feat, 🎁 modi

#94 modi: 버튼 컴포넌트 수정
  src/components/Buttons/Button.tsx
  src/components/Buttons/SelectCountryButton.tsx
Labels: 🎁 modi, 💄 style

#97 feature : 검색 관련 컴포 수정, 페이지 마크업/스타일링
  src/components/HeaderBar/HeaderBar.tsx
  src/components/SearchBar/GoSearch.tsx
  src/components/SearchBar/SearchBar.tsx
  src/hooks/useHeaderConfig.ts
  src/pages/HomePage.tsx
  src/pages/Search.tsx
  src/pages/SearchResult.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style, 🧩 markup

#98 feat : 아티클 컴포넌트 수정, 페이지 업데이트된 컴포 반영
  src/components/Lists/Article.tsx
  src/components/Lists/ArticleList.tsx
  src/pages/Login.tsx
  src/pages/SearchResult.tsx
  src/pages/SignUp.tsx
Labels: 🎨 feat, 🎁 modi

#100 feat : 로그인, 회원가입 구현
  src/api/auth.ts
  src/api/createUser.ts
  src/api/getTipRandom.ts
  src/components/AgreeTo/AgreeTo.tsx
  src/components/AgreeTo/CheckList.tsx
  src/components/Inputs/AddressInput.tsx
  src/components/Inputs/EmailInput.tsx
  src/components/Inputs/IdInput.tsx
  src/components/Inputs/NickNameInput.tsx
  src/components/Inputs/PhoneNumberInput.tsx
  src/components/Inputs/PwdConfirmInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/StandardInput.tsx
  src/components/Inputs/UserNameInput.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/hooks/useHeaderConfig.ts
  src/pages/HomePage.tsx
  src/pages/Login.tsx
  src/pages/PartyList.tsx
  src/pages/SignUp.tsx
  src/pages/Tutorial.tsx
  src/router.tsx
Labels: 🎨 feat, 🎁 modi

#101 feat: 설정 페이지 마크업 스타일링
  src/pages/Setting.tsx
Labels: 🎨 feat

#102 feat : 커뮤니티 기능 개선, 데이터 fetching, 유틸리티 함수 리팩토링
  src/components/Lists/Article.tsx
  src/components/Lists/TipArticleList.tsx
  src/components/PostingCard/MiniPostingCard.tsx
  src/components/PostingCard/SquarePostingCard.tsx
  src/hooks/useFetch.ts
  src/pages/BoastDetail.tsx
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/RecommendFeed.tsx
  src/pages/Posting/InstaPosting.tsx
  src/utils/getPbImageURL.ts
Labels: 🎨 feat, 🔥 remove, 🎁 modi, 🐛 fix, ♻️ refactor

#103 markup style: 마이페이지 파티 통계 마크업 스타일링
  src/components/PartyResult/PartyResult.tsx
  src/components/RatingStar/RatingStar.tsx
  src/components/SavingMoneyCard/SavingMoneyCard.tsx
  src/pages/MyPage.tsx
Labels: 💄 style, 🧩 markup

#106 feat: 파티 참여 페이지 input 연결, 주소 input 컴포넌트 api 적용, 모달 레이아웃 작업
  index.html
  package.json
  pnpm-lock.yaml
  src/components/Inputs/AddressInput.tsx
  src/layout/Modal.tsx
  src/pages/JoinParty.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style

#107 modi: mypage 내부에 컴포넌트 추가
  src/pages/MyPage.tsx
Labels: 🎁 modi

#108 markup: 회원탈퇴 마크업
  src/pages/Withdraw.tsx
Labels: 🧩 markup

#111 refactor : RatingStar 컴포넌트 구조개선을 위한 분리
  src/components/RatingStar/RatingStar.tsx
  src/components/RatingStar/Star.tsx
Labels: ♻️ refactor

#115 modi : 커뮤니티 기능 개선, 데이터 연동, UI 컴포넌트 리팩토링 및 스타일 최적화
  src/components/DefaultProfileSVG/DefaultProfileSVG.tsx
  src/components/Label/LabelList.tsx
  src/components/Lists/Article.tsx
  src/components/Lists/TipArticleList.tsx
  src/components/NameCard/NameCard.tsx
  src/components/PostingCard/PostingCard.tsx
  src/components/PostingCard/SquarePostingCard.tsx
  src/pages/BoastDetail.tsx
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/Posting/BlogPosting.tsx
  src/pages/TipDetail.tsx
  src/utils/dateFormatter.ts
  src/utils/getPbImageURL.ts
  tailwind.config.js
Labels: 🎨 feat, 🎁 modi, 🐛 fix, 💄 style, ♻️ refactor

#117 refactor : 피드백 반영하여 코드 개선
  src/components/CommunityNav/CommunityNavList.tsx
  src/components/DefaultProfileSVG/DefaultProfileSVG.tsx
  src/components/Lists/TipArticleList.tsx
  src/components/Magazine/Magazine.tsx
  src/components/NameCard/NameCard.tsx
  src/components/Payment/Payment.tsx
  src/components/Payment/PaymentListItem.tsx
  src/components/PostActionBar/PostActionBar.tsx
  src/components/PostingCard/MiniPostingCard.tsx
  src/components/PostingCard/PostingCard.tsx
  src/components/PostingCard/SquarePostingCard.tsx
  src/components/Review/Review.tsx
  src/components/shipstate/Shipstate.tsx
  src/pages/BoastDetail.tsx
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/Following.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/Community/RecommendFeed.tsx
  src/pages/Community/UserTip.tsx
  src/pages/Posting/InstaPosting.tsx
Labels: ♻️ refactor

#119 refactor : 피드백 반영해 개선
  .gitignore
  src/components/AgreeTo/AgreeTo.tsx
  src/components/AgreeTo/CheckList.tsx
  src/components/HeaderBar/HeaderBar.tsx
  src/components/Lists/Article.tsx
  src/components/Lists/PartyArticleList.tsx
  src/components/LoginNavi/LoginNavi.tsx
  src/components/NavigationBar/FloatingMenu.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/SimpleLogin/SimpleLogin.tsx
  src/pages/Landing.tsx
  src/pages/Tutorial.tsx
  src/router.tsx
Labels: ♻️ refactor

#121 docs : netlify.toml 문서 추가
  netlify.toml
Labels: 🐳 chore

#123 메인페이지 데이터 연동하면서 관련 컴포, 페이지 수정
  public/assets/country/american-flag.png
  public/assets/country/china-flag.png
  public/assets/country/japan-flag.png
  src/api/getPartyByKeyword.ts
  src/api/getUserIdByNickName.ts
  src/components/Buttons/SelectCountryButton.tsx
  src/components/PostingCard/PostingCard.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/components/SearchBar/SearchBar.tsx
  src/hooks/useHeaderConfig.ts
  src/layout/RootLayout.tsx
  src/pages/EmptyPage.tsx
  src/pages/HomePage.tsx
  src/pages/PartyList.tsx
  src/pages/Search.tsx
  src/pages/SearchResult.tsx
  src/router.tsx
  src/utils/getPbImageURL.ts
Labels: 🎨 feat, 🎁 modi, 💄 style

#125 feat : 결제 상세 페이지 구현
  public/assets/card.png
  public/assets/visa.png
  src/components/Payment/Card.tsx
  src/components/Payment/Payment.tsx
  src/components/Payment/PaymentListItem.tsx
  src/pages/PaymentDetail.tsx
Labels: 🎨 feat, 💄 style, 🧩 markup

#128 feat: 4-1차 스프린트 작업
  package.json
  pnpm-lock.yaml
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Inputs/AddressInput.tsx
  src/components/Inputs/EmailInput.tsx
  src/components/Inputs/IdInput.tsx
  src/components/Inputs/NickNameInput.tsx
  src/components/Inputs/PhoneNumberInput.tsx
  src/components/Inputs/PwdConfirmInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/StandardInput.tsx
  src/components/Inputs/UserNameInput.tsx
  src/components/Label/Label.tsx
  src/components/Label/LabelList.tsx
  src/components/Lists/Article.tsx
  src/components/Lists/Item.tsx
  src/components/Lists/ItemList.tsx
  src/components/Lists/PartyArticleList.tsx
  src/components/Lists/PartyLeader.tsx
  src/components/Lists/PartyLeaderList.tsx
  src/components/Lists/Standard.tsx
  src/layout/FocusTrap.tsx
  src/layout/Modal.tsx
  src/pages/JoinParty.tsx
  src/pages/OrderDetail.tsx
  src/pages/PartyCollect.tsx
  src/pages/PartyList.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style, 🧩 markup

#131 feat : 알림 목록 컴포넌트 구현 및 시간 유틸 함수
  src/components/NotificationList/NotificationList.tsx
  src/pages/Notifications.tsx
  src/utils/formatRelativeTime.ts
Labels: 🎨 feat, 💄 style, 🧩 markup

#134 feat : 포스팅 작성 폼 구현 및 multiple 이미지 관련 함수 추가, 리팩토링
  package.json
  pnpm-lock.yaml
  src/api/getTipRandom.ts
  src/components/FileInput.tsx
  src/components/HashtagInput/HashtagInput.tsx
  src/components/PostingCard/MiniPostingCard.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/components/PostingCard/SquarePostingCard.tsx
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/Login.tsx
  src/pages/Posting/InstaPosting.tsx
  src/pages/WritePost.tsx
  src/utils/getPbImageURL.ts
Labels: 🎨 feat, 🎁 modi, 📝 docs, 💄 style, ♻️ refactor, 🧩 markup

#137 refactor : 커뮤니티 페이지 리팩토링
  src/pages/Community/Following.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/UserTip.tsx
  src/pages/Posting/BlogPosting.tsx
Labels: ♻️ refactor

#138 홈페이지 매거진, 추천파티장, 파티리스트, 나라 선택시 페이지 이동 구현
  src/api/getBestUserRandom.ts
  src/api/getPartyByUserId.ts
  src/components/Buttons/SelectCountryButton.tsx
  src/components/Lists/BestPartyLeaderRandom.tsx
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/PartyLeader.tsx
  src/components/LoginNavi/LoginNavi.tsx
  src/components/Magazine/Magazine.tsx
  src/components/Magazine/MagazineList.tsx
  src/pages/HomePage.tsx
  src/pages/PartyList.tsx
  src/pages/Search.tsx
  src/pages/SearchResult.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style

#144 feat : 알림 목록 컴포넌트 기능 개선 및 데이터 연결
  src/components/NotificationList/NotificationList.tsx
  src/pages/Notifications.tsx
Labels: 🎨 feat, ♻️ refactor

#145 feat: 프로필 편집 페이지 구현
  src/pages/ProfileEdit.tsx
Labels: 🎨 feat

#146 refactor: axios 사용하여 회원탈퇴 구현
  src/pages/Withdraw.tsx
  src/styles/global.css
Labels: ♻️ refactor

#147 modi: 설정 페이지 라우터 연결
  src/components/ToggleSwitch/ToggleSwitch.tsx
  src/pages/AccountSettings.tsx
  src/pages/Announcements.tsx
  src/pages/BlockedUsers.tsx
  src/pages/ChangeCountry.tsx
  src/pages/ClearCache.tsx
  src/pages/DoNotDisturbSettings.tsx
  src/pages/NotificationSettings.tsx
  src/pages/OtherSettings.tsx
  src/pages/Setting.tsx
  src/pages/UpdateVersion.tsx
  src/router.tsx
Labels: 🎁 modi

#148 modi: notice list 버튼에 따라 바뀌게 수정
  src/components/MypageNoticeList/MypageNoticeList.tsx
  src/components/PartyResult/PartyResult.tsx
  src/pages/MyPage.tsx
Labels: 🎁 modi

#151 중복 검사, 회원가입 안내메시지 추가, 튜토리얼 페이지 로직 에러 해결
  src/api/getFieldValueByField.ts
  src/api/getTipRandom.ts
  src/components/Inputs/EmailInput.tsx
  src/components/Inputs/IdInput.tsx
  src/components/Inputs/NickNameInput.tsx
  src/components/Inputs/PhoneNumberInput.tsx
  src/components/Inputs/PwdConfirmInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/UserNameInput.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/router.tsx
  src/utils/checkDuplicate.ts
Labels: 🎨 feat, 🎁 modi, 🐛 fix

#149 feat : 스와이퍼 기능 구현 및 블로그형 포스팅 이미지-텍스트 교차 배열 기능 추가
  src/components/Dropdown/Dropdown.tsx
  src/components/FileInput.tsx
  src/components/Lists/Article.tsx
  src/components/Lists/TipArticleList.tsx
  src/components/Magazine/Magazine.tsx
  src/components/Magazine/MagazineList.tsx
  src/components/PostingCard/PostingCard.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/hooks/useHeaderConfig.ts
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/MagazineDetail.tsx
  src/pages/Posting/BlogPosting.tsx
  src/pages/Posting/InstaPosting.tsx
  src/pages/WritePost.tsx
  src/router.tsx
  src/utils/getRandomItems.ts
  src/utils/seperateTextAndImages.ts
Labels: 🎨 feat, ♻️ refactor

#150 feat: 개인 정보 수정 페이지 구현
  src/pages/PersonalInfoEdit.tsx
Labels: 🎨 feat

#153 렌더링 오류 해결중
  public/assets/country/american-flag.webp
  public/assets/country/china-flag.webp
  public/assets/country/japan-flag.webp
  src/api/getBestUserRandom.ts
  src/api/getPartyByKeyword.ts
  src/api/getPartyByUserId.ts
  src/api/getTipRandom.ts
  src/api/getUserById.ts
  src/components/Buttons/SelectCountryButton.tsx
  src/components/Lists/Article.tsx
  src/components/Lists/BestPartyLeaderRandom.tsx
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/RandomTip.tsx
  src/pages/HomePage.tsx
Labels: 🐛 fix

#154 fix : 새로고침 이슈 해결중
  src/api/auth.ts
  src/api/createUser.ts
  src/api/getBestUserRandom.ts
  src/api/getFieldValueByField.ts
  src/api/getPartyByKeyword.ts
  src/api/getPartyByUserId.ts
  src/api/getPartyNameByUserId.ts
  src/api/getTip.ts
  src/api/getUserById.ts
  src/api/getUserIdByNickName.ts
  src/components/Lists/BestPartyLeaderRandom.tsx
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/RandomTip.tsx
  src/components/NameCard/NameCard.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/hooks/useHeaderConfig.ts
  src/utils/checkDuplicate.ts
Labels: 🐛 fix

#156 feat : 좋아요 기능 추가 및 조회수 랜덤숫자 렌더링
  src/components/PostActionBar/PostActionBar.tsx
  src/pages/Community/UserTip.tsx
  src/pages/Posting/BlogPosting.tsx
  src/pages/Posting/InstaPosting.tsx
  src/pages/TipDetail.tsx
Labels: 🎨 feat, ♻️ refactor

#159 refactor : 홈페이지 오류 개선
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/RandomTip.tsx
  src/components/Lists/TipArticleList.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/HomePage.tsx
  src/pages/Posting/BlogPosting.tsx
  src/pages/Posting/InstaPosting.tsx
Labels: ♻️ refactor

#161 feat : 인기포스트 좋아요 순으로 정렬
  src/components/Magazine/Magazine.tsx
  src/components/PostingCard/PostingCard.tsx
  src/pages/Community/PopularPost.tsx
Labels: 🎨 feat, 💄 style, ♻️ refactor

#162 각 컴포넌트별 새로고침 버튼 추가, 확장자 변경
  index.html
  public/assets/card.png
  public/assets/card.webp
  public/assets/country/american-flag.png
  public/assets/country/china-flag.png
  public/assets/country/japan-flag.png
  public/assets/landinglogo.png
  public/assets/login/apple.svg
  public/assets/login/google.svg
  public/assets/login/kakao.svg
  public/assets/loginsignuplogo.png
  public/assets/shipmatelogo.webp
  public/assets/tutorial/landing-1.webp
  public/assets/tutorial/landinglogo.webp
  public/assets/tutorial/loginsignuplogo.webp
  public/assets/tutorial/tutorial-1.webp
  public/assets/tutorial/tutorial-2.webp
  public/assets/tutorial/tutorial-3.webp
  public/assets/tutorial/tutorial-4.webp
  public/assets/visa.png
  public/assets/visa.webp
  src/api/getPartyByKeyword.ts
  src/components/Buttons/ReloadButton.tsx
  src/components/Buttons/SelectCountryButton.tsx
  src/components/HeaderBar/HeaderBar.tsx
  src/components/Lists/BestPartyLeaderRandom.tsx
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/PartyArticleList.tsx
  src/components/Lists/PartyLeader.tsx
  src/components/Lists/RandomTip.tsx
  src/components/Lists/TipArticleList.tsx
  src/components/NavigationBar/FloatingMenu.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/Payment/Card.tsx
  src/components/PostingCard/MiniPostingCard.tsx
  src/components/PostingCard/PostingCard.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/components/PostingCard/SquarePostingCard.tsx
  src/components/SimpleLogin/SimpleLogin.tsx
  src/pages/Community/Following.tsx
  src/pages/EmptyPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/HomePage.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/Notifications.tsx
  src/pages/SignUp.tsx
  src/pages/Tutorial.tsx
Labels: 🎨 feat, 🎁 modi, ♻️ refactor

#165 refactor : 성능 최적화 및 리팩토링
  src/components/CommunityNav/CommunityNav.tsx
  src/components/CommunityNav/CommunityNavList.tsx
  src/components/DefaultProfileSVG/DefaultProfileSVG.tsx
  src/components/FileInput/FileInput.tsx
  src/components/HashtagInput/HashtagInput.tsx
  src/components/Lists/TipArticleList.tsx
  src/components/NameCard/NameCard.tsx
  src/components/NotificationList/NotificationList.tsx
  src/components/Payment/Card.tsx
  src/components/Payment/Payment.tsx
  src/components/Payment/PaymentListItem.tsx
  src/components/PostActionBar/PostActionBar.tsx
  src/components/PostingCard/MiniPostingCard.tsx
  src/components/RatingStar/RatingStar.tsx
  src/components/Review/Review.tsx
  src/components/shipstate/Shipstate.tsx
  src/hooks/useFetch.ts
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/Community/RecommendFeed.tsx
  src/pages/Community/UserTip.tsx
  src/pages/MagazineDetail.tsx
  src/pages/Notifications.tsx
  src/pages/Posting/BlogPosting.tsx
  src/pages/Posting/InstaPosting.tsx
  src/pages/WritePost.tsx
  src/utils/dateFormatter.ts
Labels: ♻️ refactor

#167 feat: 내프로필 db연동중
  src/components/MyprofileFollower/MyprofileFollower.tsx
  src/components/NameCard/NameCard.tsx
  src/pages/MyPage.tsx
  src/pages/MyProfile.tsx
  src/pages/ProfileEdit.tsx
  src/router.tsx
Labels: 🎨 feat

#166 refactor : 성능 최적화(필수 원본 미리 로딩), 로딩 스피너 적용중
  index.html
  public/assets/logo.svg
  src/components/Buttons/SelectCountryButton.tsx
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/RandomTip.tsx
  src/components/LoadingSpinner.tsx
  src/components/Magazine/MagazineList.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SimpleLogin/SimpleLogin.tsx
  src/pages/HomePage.tsx
  src/pages/SearchResult.tsx
  src/pages/SignUp.tsx
  src/router.tsx
Labels: 🎁 modi, ♻️ refactor

#168 feat: 맡은 페이지 db 연결 및 컴포넌트 코드 수정
  src/components/AddImage/AddImage.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Inputs/AddressInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/StandardInput.tsx
  src/components/Inputs/UserNameInput.tsx
  src/components/Lists/PartyLeader.tsx
  src/components/PartyInfo/PartyInfoList.tsx
  src/pages/JoinParty.tsx
  src/pages/OrderDetail.tsx
  src/pages/PartyCollect.tsx
  src/pages/PartyDetail.tsx
Labels: 🎨 feat, 🎁 modi, 💄 style, 🧩 markup

#171 refactor : 성능개선 및 로딩스피너 제거
  src/pages/Community/Magazine.tsx
  src/pages/Community/RecommendFeed.tsx
  src/pages/Community/UserTip.tsx
  src/pages/Notifications.tsx
Labels: ♻️ refactor

#172 refactor : 파티리더 수정에 따른 재수정, 로딩스피너 개선
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/PartyLeader.tsx
  src/components/LoadingSpinner.tsx
Labels: ♻️ refactor

#173 modi: 채팅 리스트 / 채팅창 수정
  src/pages/ChatHome.tsx
  src/pages/ChatRoom.tsx
Labels: 🎁 modi

#174 modi : 화면이동하면 플로팅메뉴 비활성화
  src/components/NavigationBar/FloatingMenu.tsx
  src/components/NavigationBar/NavigationBar.tsx
Labels: 🎁 modi

#178 refactor : 폴더 구조 변경 및 리팩토링
  src/pages/Posting/BlogPosting.tsx
  src/pages/Posting/BoastDetail.tsx
  src/pages/Posting/InstaPosting.tsx
  src/pages/Posting/MagazineDetail.tsx
  src/pages/Posting/TipDetail.tsx
  src/pages/Posting/WritePost.tsx
  src/router.tsx
Labels: ♻️ refactor

#179 modi: 채팅 수정
  src/pages/ChatHome.tsx
  src/pages/ChatRoom.tsx
Labels: 🎁 modi

#180 modi: 1차 코드 수정
  src/components/Inputs/EmailInput.tsx
  src/components/Inputs/PwdConfirmInput.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Inputs/StandardInput.tsx
  src/components/Lists/PartyLeader.tsx
  src/components/Lists/PartyLeaderList.tsx
  src/components/PostingCard/PostingCard.tsx
  src/pages/JoinParty.tsx
  src/pages/PartyCollect.tsx
  src/pages/PartyDetail.tsx
Labels: 🎁 modi, 🐛 fix, 💄 style, ♻️ refactor

#184 feat : 커뮤니티 페이지 애니메이션 추가 및 좋아요 버튼 hover 스타일 적용
  src/components/Lists/TipArticleList.tsx
  src/components/Payment/Card.tsx
  src/components/PostActionBar/PostActionBar.tsx
  src/components/PostingCard/PostingCard.tsx
  src/components/Review/Review.tsx
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/Community/UserTip.tsx
  src/pages/Posting/InstaPosting.tsx
  src/pages/Posting/WritePost.tsx
Labels: 🎨 feat

#182 style,modi : 홈페이지- 매거진 스와이퍼 버튼 수정, 프로필 보기- 내가 멤버인 파티도 불러오도록 수정, 로딩스피너 컴포넌트 - 스켈레톤으로 이름 변경
  src/api/getAllPartyByUserId.ts
  src/components/Lists/BestPartyRandom.tsx
  src/components/Lists/RandomTip.tsx
  src/components/LoadingSpinner.tsx
  src/components/Magazine/Magazine.tsx
  src/components/Magazine/MagazineList.tsx
  src/components/PostingCard/PostingRandom.tsx
  src/pages/ChatHome.tsx
  src/pages/HomePage.tsx
  src/pages/MyProfile.tsx
  src/pages/PartyList.tsx
  src/pages/SearchResult.tsx
  src/styles/global.css
Labels: 🎁 modi, 💄 style

#186 refactor, style : 접근성 색상 대비, alt 추가, 튜토리얼 다시 볼 수 있도록 수정
  src/components/Lists/BestPartyRandom.tsx
  src/components/Magazine/Magazine.tsx
  src/components/SearchBar/GoSearch.tsx
  src/components/SearchBar/SearchBar.tsx
  src/pages/HomePage.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/Tutorial.tsx
  src/router.tsx
Labels: ♻️ refactor

#187 mod : 간단로그인 이미지 변경, 파티리더 이미지 깨지는거 수정
  public/assets/login/apple.webp
  public/assets/login/google.webp
  public/assets/login/kakao.webp
  src/components/SimpleLogin/SimpleLogin.tsx
Labels: 🎁 modi

#188 modi : 홈페이지 파티리더 깨지는거 코드 수정
  src/components/Lists/BestPartyRandom.tsx
Labels: 🎁 modi

#189 refactor : 리드미 작성 및 알림, 결제페이지 수정
  README.md
  src/components/Lists/TipArticleList.tsx
  src/components/NotificationList/NotificationList.tsx
  src/pages/Notifications.tsx
  src/pages/PaymentDetail.tsx
  src/router.tsx
Labels: 📝 docs, ♻️ refactor

#190 refactor: 이것저것많이함
  src/components/MyprofileFollower/MyprofileFollower.tsx
  src/components/PartyResult/PartyResult.tsx
  src/components/SavingMoneyCard/SavingMoneyCard.tsx
  src/pages/AccountSettings.tsx
  src/pages/MyPage.tsx
  src/pages/MyProfile.tsx
  src/pages/PersonalInfoEdit.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Setting.tsx
  src/pages/Withdraw.tsx
Labels: 🐛 fix, ♻️ refactor

#192 modi: 채팅방 라우팅 및 결제 페이지 라우팅
  src/components/AddImage/AddImage.tsx
  src/components/Inputs/PwdInput.tsx
  src/components/Lists/Item.tsx
  src/components/Lists/ItemList.tsx
  src/pages/JoinParty.tsx
  src/pages/OrderDetail.tsx
  src/pages/PartyCollect.tsx
  src/pages/PartyDetail.tsx
Labels: 🎁 modi, ♻️ refactor

#194 refactor : 줄바꿈 오류 수정 및 스와이퍼 추가
  src/components/Lists/TipArticleList.tsx
  src/components/PostingCard/PostingCard.tsx
  src/pages/Community/CommunityHome.tsx
Labels: ♻️ refactor

#200 refactor : 알림메세지 수정
  src/components/NotificationList/NotificationList.tsx
Labels: ♻️ refactor

#195 modi : 드롭다운 제대로 받을 수 있도록 반영
  src/components/Inputs/EmailInput.tsx
  src/utils/checkDuplicate.ts
Labels: 🎁 modi

#198 fix: 배포 후 오류 수정
  src/components/AddImage/AddImage.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Inputs/AddressInput.tsx
  src/components/Lists/Item.tsx
  src/layout/Modal.tsx
  src/pages/JoinParty.tsx
  src/pages/PartyDetail.tsx
Labels: 🐛 fix

#196 modi: 채팅 / 인기 검색어 / 헬멧 / 헤더
  src/components/PostActionBar/PostActionBar.tsx
  src/hooks/useHeaderConfig.ts
  src/pages/AccountSettings.tsx
  src/pages/ChangeCountry.tsx
  src/pages/ChatHome.tsx
  src/pages/ChatRoom.tsx
  src/pages/MyProfile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Search.tsx
  src/pages/Setting.tsx
  src/pages/Withdraw.tsx
  src/router.tsx
Labels: 🎁 modi

#201 modi: 오타 수정
  src/pages/OrderDetail.tsx
  src/pages/PartyDetail.tsx
Labels: 🎁 modi

#203 refactor : ogp 추가
  src/pages/Community/CommunityHome.tsx
  src/pages/Community/Magazine.tsx
  src/pages/Community/PopularPost.tsx
  src/pages/Community/RecommendFeed.tsx
  src/pages/Community/UserTip.tsx
  src/pages/HomePage.tsx
  src/pages/Landing.tsx
  src/pages/PartyDetail.tsx
  src/pages/PartyList.tsx
  src/pages/Posting/BoastDetail.tsx
  src/pages/Posting/MagazineDetail.tsx
  src/pages/Posting/TipDetail.tsx
  src/pages/Posting/WritePost.tsx
  src/pages/SearchResult.tsx
  src/pages/SignUp.tsx
  src/pages/Tutorial.tsx
Labels: ♻️ refactor

#204 fix : ogp 문제 해결중
  src/pages/HomePage.tsx
Labels: 🐛 fix

#205 style: 채팅방 input 위치 수정
  src/pages/ChatRoom.tsx
Labels: 💄 style

#206 refactor : 튜토리얼 로컬 스토리지에 저장하도록 수정, index 에 og 태그추가
  index.html
  src/pages/Tutorial.tsx
Labels: ♻️ refactor

#207 refactor : 라우터에서도 튜토리얼 완료 여부 로컬에서 가져오게 변경
  src/router.tsx
Labels: 🎁 modi, ♻️ refactor

#208 refactor : 랜딩 튜토리얼 버튼 스토리지 세션으로 변경
  src/pages/Landing.tsx
Labels: 🎁 modi, ♻️ refactor

#209 refactor : 아이디, 비밀번호 찾기 클릭시 알럿
  src/components/LoginNavi/LoginNavi.tsx
Labels: 🎁 modi

#213 docs : 리드미 수정 및 OrderDetail 오류 수정
  README.md
  src/pages/OrderDetail.tsx
Labels: 📝 docs
